import { Inter } from 'next/font/google'
import Link from 'next/link'
import dynamic from 'next/dynamic'
import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const Scene = dynamic(() => import('@/components/ui/scene'), { ssr: false })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body style={{ overscrollBehaviorY: "none"}} className={inter.className}>
        <ThemeProvider attribute='class' defaultTheme='light'>
          <div className='flex flex-col min-h-screen'>
            <header className='px-4 lg:px-6 h-14 flex items-center'>
              <Link className='flex items-center justify-center' href='#'>
                <Logo className='h-6 w-6' />
                <span className='sr-only'>pmndrs</span>
              </Link>
              <nav className='ml-auto flex gap-4 sm:gap-6'>
                <Link className='text-sm font-medium hover:underline underline-offset-4' href='#'>
                  Features
                </Link>
                <Link className='text-sm font-medium hover:underline underline-offset-4' href='#'>
                  Pricing
                </Link>
                <Link className='text-sm font-medium hover:underline underline-offset-4' href='#'>
                  About
                </Link>
                <Link className='text-sm font-medium hover:underline underline-offset-4' href='#'>
                  Contact
                </Link>
              </nav>
            </header>
            {children}
          </div>
        </ThemeProvider>
        <Scene />
      </body>
    </html>
  )
}

function Logo({ color = 'black', ...props }) {
  return (
    <svg aria-hidden='true' viewBox='0 0 800 800' fill={color} xmlns='http://www.w3.org/2000/svg' {...props}>
      <rect x='280' y='560' width='240' height='240' fill='inherit' />
      <rect x='280' y='280' width='240' height='240' fill='inherit' />
      <rect y='280' width='240' height='240' fill='inherit' />
      <path fillRule='evenodd' clipRule='evenodd' d='M560 0H280V240H560V520H800V0H560Z' fill='inherit' />
    </svg>
  )
}
