'use client'

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/L9jdwEGYcqw
 */
import Link from 'next/link'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import dynamic from 'next/dynamic'

const Common = dynamic(() => import('@/components/canvas/common'), { ssr: false })
const Dog = dynamic(() => import('@/components/canvas/dog'), { ssr: false })
const Duck = dynamic(() => import('@/components/canvas/duck'), { ssr: false })
const Hello = dynamic(() => import('@/components/canvas/hello'), { ssr: false })
const View = dynamic(() => import('@react-three/drei').then((mod) => mod.View), {
  ssr: false,
  loading: () => (
    <div className='flex h-96 w-full flex-col items-center justify-center'>
      <svg style={{ width: 40, height: 40 }} className='-ml-1 mr-3 h-5 w-5 animate-spin text-black' fill='none' viewBox='0 0 24 24'>
        <circle className='opacity-25' cx='12' cy='12' r='10' stroke='currentColor' strokeWidth='4' />
        <path
          className='opacity-75'
          fill='currentColor'
          d='M4 12a8 8 0 0 1 8-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 0 1 4 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z'
        />
      </svg>
    </div>
  ),
})

export default function Home() {
  return (
    <main className='flex-1'>
      <section className='flex items-center justify-center w-full h-screen border-y'>
        <div className='container'>
          <div className='pointer-events-none absolute -top-20 left-0 flex items-center justify-center w-full h-screen'>
            <div className='inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800'>New release: 3.x 🎉</div>
          </div>
          <View className='w-full h-screen'>
            <Hello scale={2} />
          </View>
        </div>
      </section>
      <section className='flex items-center justify-center w-full py-12 md:py-24 lg:py-32 border-y'>
        <div className='container space-y-12 px-4 md:px-6'>
          <div className='flex flex-col items-center justify-center space-y-4 text-center'>
            <div className='space-y-2'>
              <div className='inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800'>New Features</div>
              <h2 className='text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]'>
                Faster iteration. More innovation.
              </h2>
              <p className='max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400'>
                The platform for rapid progress. Let your team focus on shipping features instead of managing infrastructure with automated
                CI/CD, built-in testing, and integrated collaboration.
              </p>
              <View orbit className='mx-auto aspect-[3/1] overflow-hidden'>
                <Duck route='/blob' scale={2} position={[0, -1.6, 0]} />
                <Common color='lightblue' controls />
              </View>
            </div>
          </div>
          <div className='mx-auto grid max-w-[1300px] gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16 lg:max-w-5xl lg:grid-cols-3'>
            <div className='grid gap-1'>
              <h3 className='text-lg font-bold'>Infinite scalability, zero config</h3>
              <p className='text-sm text-gray-500 dark:text-gray-400'>
                Enable code to run on-demand without needing to manage your own infrastructure or upgrade hardware.
              </p>
            </div>
            <div className='grid gap-1'>
              <h3 className='text-lg font-bold'>Real-time insights and controls</h3>
              <p className='text-sm text-gray-500 dark:text-gray-400'>
                Get granular, first-party, real-user metrics on site performance per deployment.
              </p>
            </div>
            <div className='grid gap-1'>
              <h3 className='text-lg font-bold'>Personalization at the edge</h3>
              <p className='text-sm text-gray-500 dark:text-gray-400'>
                Deliver dynamic, personalized content, while ensuring users only see the best version of your site.
              </p>
            </div>
            <div className='grid gap-1'>
              <h3 className='text-lg font-bold'>Real-time insights and controls</h3>
              <p className='text-sm text-gray-500 dark:text-gray-400'>
                Get granular, first-party, real-user metrics on site performance per deployment.
              </p>
            </div>
            <div className='grid gap-1'>
              <h3 className='text-lg font-bold'>Personalization at the edge</h3>
              <p className='text-sm text-gray-500 dark:text-gray-400'>
                Deliver dynamic, personalized content, while ensuring users only see the best version of your site.
              </p>
            </div>
            <div className='grid gap-1'>
              <h3 className='text-lg font-bold'>Infinite scalability, zero config</h3>
              <p className='text-sm text-gray-500 dark:text-gray-400'>
                Enable code to run on-demand without needing to manage your own infrastructure or upgrade hardware.
              </p>
            </div>
          </div>
          <div className='flex justify-center flex-col sm:flex-row items-start gap-4'>
            <Link
              className='inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300'
              href='#'>
              Contact Sales
            </Link>
            <Link
              className='inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800'
              href='#'>
              Tour the Platform
            </Link>
          </div>
        </div>
      </section>
      <section className='flex items-center justify-center w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800 border-t'>
        <div className='container grid items-center justify-center gap-4 px-4 text-center md:px-6'>
          <div className='space-y-3'>
            <h2 className='text-3xl font-bold tracking-tighter md:text-4xl/tight'>Experience the workflow the best frontend teams love.</h2>
            <p className='mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400'>
              Let your team focus on shipping features instead of managing infrastructure with automated CI/CD.
            </p>
          </div>
          <div className='mx-auto w-full max-w-sm space-y-2'>
            <form className='flex space-x-2'>
              <Input className='max-w-lg flex-1' placeholder='Enter your email' type='email' />
              <Button type='submit'>Sign Up</Button>
            </form>
            <p className='text-xs text-gray-500 dark:text-gray-400'>
              Sign up to get notified when we launch.
              <Link className='underline underline-offset-2' href='#'>
                Terms & Conditions
              </Link>
            </p>
          </div>
        </div>
      </section>
      <section className='flex items-center justify-center w-full py-12 md:py-24 lg:py-32 border-t'>
        <div className='container px-4 md:px-6'>
          <div className='flex flex-col items-center justify-center space-y-4 text-center'>
            <div className='space-y-2'>
              <div className='inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm dark:bg-gray-800'>New Features</div>
              <h2 className='text-3xl font-bold tracking-tighter sm:text-5xl'>Faster iteration. More innovation.</h2>
              <p className='max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400'>
                The platform for rapid progress. Let your team focus on shipping features instead of managing infrastructure with automated
                CI/CD, built-in testing, and integrated collaboration.
              </p>
            </div>
          </div>
          <div className='mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12'>
            <View
              orbit
              style={{ width: 550, height: 310 }}
              className='mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last'>
              <Dog scale={2} position={[0, -1.6, 0]} rotation={[0.0, -0.3, 0]} />
              <Common color='lightpink' controls />
            </View>
            <div className='flex flex-col justify-center space-y-4'>
              <ul className='grid gap-6'>
                <li>
                  <div className='grid gap-1'>
                    <h3 className='text-xl font-bold'>Collaboration</h3>
                    <p className='text-gray-500 dark:text-gray-400'>Make collaboration seamless with built-in code review tools.</p>
                  </div>
                </li>
                <li>
                  <div className='grid gap-1'>
                    <h3 className='text-xl font-bold'>Automation</h3>
                    <p className='text-gray-500 dark:text-gray-400'>Automate your workflow with continuous integration.</p>
                  </div>
                </li>
                <li>
                  <div className='grid gap-1'>
                    <h3 className='text-xl font-bold'>Scale</h3>
                    <p className='text-gray-500 dark:text-gray-400'>Deploy to the cloud with a single click and scale with ease.</p>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <section className='flex items-center justify-center w-full py-12 md:py-24 lg:py-32 border-t bg-gray-100 dark:bg-gray-800'>
        <div className='container px-4 md:px-6'>
          <div className='grid gap-10 px-10 md:gap-16 lg:grid-cols-2'>
            <div className='space-y-4'>
              <div className='inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm dark:bg-gray-800'>Performance</div>
              <h2 className='lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none'>
                Traffic spikes should be exciting, not scary.
              </h2>
            </div>
            <div className='flex flex-col items-start space-y-4'>
              <div className='inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm dark:bg-gray-800'>Security</div>
              <p className='mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400'>
                Fully managed infrastructure designed to scale dynamically with your traffic, a global edge to ensure your site is fast for
                every customer, and the tools to monitor every aspect of your app.
              </p>
              <Link
                className='inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300'
                href='#'>
                Get Started
              </Link>
            </div>
          </div>
        </div>
      </section>
    </main>
  )
}
